Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 35

Metrics/PerceivedComplexity:
  Max: 11

AllCops:
  TargetRubyVersion: 2.6

  Include:
    - '**/Rakefile'
    - '**/config.ru'

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'lib/**/*'
    - '**/Gemfile'
    - !ruby/regexp /old_and_unused\.rb$/